language: node_js
node_js:
  - "10.14.2"
cache:
  yarn: true
  directories:
    - node_modules
script:
  - console.log("skipping tests")

#deploy:
#  provider: heroku
#  app: webcook-api
#  on: develop
